"""The desktop build: the whole sketch compiled for this computer, with the hardware stubbed out.

1. arduino-builder -preprocess combines the .ino files and generates the prototypes exactly as the
   IDE does (the same .ino.cpp as the instrument build compiles).
2. longfix rewrites that file and the sketch's .h files so `long` is 32-bit, and marks the clock
   reads inside the firmware's busy-waits so that each pass of their loops takes time; memfix gives
   the arrays the firmware is known to overrun the room it reaches into.
3. The translation unit is: sketch_prelude.h, the rewritten sketch, sketch_tail.h, then the harness.
   The sketch's #include <Arduino.h>, <SPI.h> and <DueFlashStorage.h> find the stand-ins in
   tools/desktop/include; hal.cpp is compiled separately and implements them.

The HAL, the stand-ins and the harness always come from this checkout (the one running fw.py),
and only the sketch comes from the target. So when two versions of the firmware are compared, both
run on the same model of the hardware and the same harness.
"""
import glob
import os
import shutil
import subprocess

from . import arduino, longfix, memfix

TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESKTOP_DIR = os.path.join(TOOLS_DIR, 'desktop')
DEFAULT_HARNESS = os.path.join(DESKTOP_DIR, 'smoke.cpp')

# How the instrument's compiler sees the code, as far as a desktop compiler can match it:
#   -fshort-enums     enums are as small as their values allow (1 byte), as on arm-none-eabi
#   -funsigned-char   plain char is unsigned on ARM (it's signed on x86 and on Apple arm64)
#   -fwrapv           signed overflow wraps, as the instrument's code does in practice
#   -ffp-contract=off no fused multiply-add: the Cortex-M3 has no FPU and never fuses
# plus the defines of the reference build (platform.txt and boards.txt of the SAM core).
CXXFLAGS = [
    '-std=gnu++11', '-fshort-enums', '-funsigned-char', '-fno-exceptions', '-fno-rtti',
    '-fno-threadsafe-statics', '-fwrapv', '-fno-strict-aliasing', '-ffp-contract=off', '-O2', '-g',
    '-DARDUINO=' + arduino.IDE_VERSION, '-DARDUINO_SAM_DUE', '-DARDUINO_ARCH_SAM', '-D__SAM3X8E__',
    '-DF_CPU=84000000', '-DUSBCON', '-DLINNSTRUMENT_DESKTOP=1',
]


def compiler():
    for cxx in (os.environ.get('CXX'), 'clang++', 'g++'):
        if cxx and shutil.which(cxx):
            return cxx
    raise RuntimeError('no C++ compiler found (set CXX)')


def _binary_h():
    lines = ['// generated by tools/fwlib/desktop.py, like the SAM core\'s binary.h', '#ifndef Binary_h', '#define Binary_h']
    for n in range(1, 9):
        for v in range(1 << n):
            lines.append('#define B%s %d' % (format(v, '0%db' % n), v))
    lines.append('#endif')
    return '\n'.join(lines) + '\n'


def _run(cmd, what):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        out = r.stdout + r.stderr
        errors = [l for l in out.splitlines() if ' error' in l or 'error:' in l]
        raise RuntimeError('%s failed:\n%s' % (what, '\n'.join((errors or out.splitlines())[:40])))
    return r.stdout + r.stderr


# AddressSanitizer: reports any access outside a variable or allocation, and stops the program
SANITIZE_FLAGS = ['-fsanitize=address', '-fno-omit-frame-pointer']


def build(tc, sketch_dir, out_dir, harness=DEFAULT_HARNESS, log=print, sanitize=False):
    """Builds the desktop executable (with AddressSanitizer if sanitize). Returns {'exe', 'sketch_object',
    'rewrites', 'busy_waits', 'contained', 'src_dir'}."""
    src = os.path.join(out_dir, 'src')
    gen = os.path.join(out_dir, 'generated')
    for d in (src, gen):
        if os.path.exists(d):
            shutil.rmtree(d)
        os.makedirs(d)

    combined = arduino.preprocess_sketch(tc, sketch_dir, os.path.join(out_dir, 'preprocess'))
    rewrites = {}
    for h in sorted(glob.glob(os.path.join(sketch_dir, '*.h'))):
        text, counts = longfix.rewrite(open(h, encoding='utf-8', errors='surrogateescape').read())
        rewrites[os.path.basename(h)] = counts
        with open(os.path.join(src, os.path.basename(h)), 'w', encoding='utf-8', errors='surrogateescape') as f:
            f.write(text)
    text, counts = longfix.rewrite(open(combined, encoding='utf-8', errors='surrogateescape').read())
    text, busy = longfix.mark_busy_waits(text)
    text, contained = memfix.contain(text)
    rewrites['linnstrument-firmware.ino.cpp'] = counts
    unit = ('#include "sketch_prelude.h"\n' + text +
            '\n#line 1 "sketch_tail.h"\n#include "sketch_tail.h"\n#line 1 "%s"\n#include "%s"\n' % (harness, harness))
    unit_path = os.path.join(src, 'sketch.cpp')
    with open(unit_path, 'w', encoding='utf-8', errors='surrogateescape') as f:
        f.write(unit)
    with open(os.path.join(gen, 'binary.h'), 'w') as f:
        f.write(_binary_h())

    cxx = compiler()
    includes = ['-I' + src, '-I' + DESKTOP_DIR, '-I' + os.path.join(DESKTOP_DIR, 'include'), '-I' + gen]
    sketch_o = os.path.join(out_dir, 'sketch.o')
    hal_o = os.path.join(out_dir, 'hal.o')
    exe = os.path.join(out_dir, 'linnstrument-desktop')
    log('compiling the sketch for the desktop (%s)' % os.path.basename(cxx))
    extra = SANITIZE_FLAGS if sanitize else []
    _run([cxx] + CXXFLAGS + extra + ['-w'] + includes + ['-c', unit_path, '-o', sketch_o], 'desktop compile of the sketch')
    _run([cxx] + CXXFLAGS + extra + ['-Wall', '-Wextra'] + includes + ['-c', os.path.join(DESKTOP_DIR, 'hal.cpp'), '-o', hal_o],
         'desktop compile of hal.cpp')
    _run([cxx] + extra + [sketch_o, hal_o, '-o', exe], 'desktop link')
    return {'exe': exe, 'sketch_object': sketch_o, 'rewrites': rewrites, 'busy_waits': busy, 'contained': contained,
            'src_dir': src}


def run(exe, args, cwd=None):
    r = subprocess.run([exe] + list(args), capture_output=True, text=True, cwd=cwd)
    if r.returncode != 0:
        raise RuntimeError('%s %s failed (exit %d):\n%s' % (os.path.basename(exe), ' '.join(args), r.returncode,
                                                             (r.stdout + r.stderr)[-3000:]))
    return r.stdout


def boot_and_run(exe, out_dir, settings=None, seconds=3.0, midi_log=None, calibration='as-exported'):
    """The two runs of a replay: provisioning (erased flash, restore settings the way the updater
    does, Update OS off), then a normal boot from the resulting flash. Returns (provisioning output,
    run output)."""
    image = os.path.join(out_dir, 'flash-provisioned.bin')
    args = ['--provision', '--calibration', calibration, '--seconds', '0', '--flash-out', image]
    if settings:
        args += ['--restore', os.path.abspath(settings)]
    provision = run(exe, args)
    args = ['--flash-in', image, '--seconds', str(seconds)]
    if midi_log:
        args += ['--midi-log', midi_log]
    return provision, run(exe, args)
