// Desktop stand-in for the Arduino SAM core's Arduino.h (arduino:sam 1.6.11), for the desktop build of
// the LinnStrument sketch. It declares the same API with the same types, except that the core's
// `long` becomes int32_t/uint32_t, as the sketch's own `long` is rewritten (tools/fwlib/longfix.py).
// Everything declared here is implemented in hal.cpp. Keep the macros identical to the core's
// wiring_constants.h: the firmware relies on their exact semantics (mixed-type min/max, 1-byte bool).
#ifndef Arduino_h
#define Arduino_h

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "avr/pgmspace.h"
#include "binary.h"          // generated by the desktop build, like the core's binary.h
#include "itoa.h"

// ---- wiring_constants.h
#define HIGH 0x1
#define LOW  0x0

#define INPUT 0x0
#define OUTPUT 0x1
#define INPUT_PULLUP 0x2

#define true 0x1
#define false 0x0

#define PI 3.1415926535897932384626433832795
#define HALF_PI 1.5707963267948966192313216916398
#define TWO_PI 6.283185307179586476925286766559
#define DEG_TO_RAD 0.017453292519943295769236907684886
#define RAD_TO_DEG 57.295779513082320876798154814105
#define EULER 2.718281828459045235360287471352

#define SERIAL  0x0
#define DISPLAY 0x1

enum BitOrder {
  LSBFIRST = 0,
  MSBFIRST = 1
};

#define CHANGE 2
#define FALLING 3
#define RISING 4

#define DEFAULT 1
#define EXTERNAL 0

#ifdef abs
#undef abs
#endif

#ifndef min
#define min(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef max
#define max(a,b) ((a)>(b)?(a):(b))
#endif
#define abs(x) ((x)>0?(x):-(x))
#define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
#define round(x)     ((x)>=0?(int32_t)((x)+0.5):(int32_t)((x)-0.5))
#define radians(deg) ((deg)*DEG_TO_RAD)
#define degrees(rad) ((rad)*RAD_TO_DEG)
#define sq(x) ((x)*(x))

#define interrupts()
#define noInterrupts()

#define lowByte(w) ((uint8_t) ((w) & 0xff))
#define highByte(w) ((uint8_t) ((w) >> 8))

#define bitRead(value, bit) (((value) >> (bit)) & 0x01)
#define bitSet(value, bit) ((value) |= (((uint32_t)1) << (bit)))
#define bitClear(value, bit) ((value) &= ~(((uint32_t)1) << (bit)))
#define bitWrite(value, bit, bitvalue) (bitvalue ? bitSet(value, bit) : bitClear(value, bit))

typedef unsigned int word;

#define bit(b) (((uint32_t)1) << (b))

typedef bool boolean;
typedef uint8_t byte;

// ---- Arduino.h / wiring.h / wiring_digital.h / wiring_analog.h / WMath.h / Tone.h
void yield(void);
extern void setup(void);
extern void loop(void);

extern uint32_t millis(void);
extern uint32_t micros(void);
extern void delay(uint32_t dwMs);
extern void delayMicroseconds(uint32_t dwUs);

extern void pinMode(uint32_t dwPin, uint32_t dwMode);
extern void digitalWrite(uint32_t dwPin, uint32_t dwVal);
extern int digitalRead(uint32_t ulPin);
extern uint32_t analogRead(uint32_t ulPin);
extern void analogWrite(uint32_t ulPin, uint32_t ulValue);
extern void analogReadResolution(int res);
extern void analogWriteResolution(int res);

extern int32_t random(int32_t howbig);
extern int32_t random(int32_t howsmall, int32_t howbig);
extern void randomSeed(uint32_t dwSeed);
extern int32_t map(int32_t x, int32_t in_min, int32_t in_max, int32_t out_min, int32_t out_max);

extern void tone(uint32_t _pin, uint32_t frequency, uint32_t duration = 0);
extern void noTone(uint32_t _pin);

#define DEC 10
#define HEX 16
#define OCT 8
#define BIN 2

#include "WString.h"
#include "Print.h"
#include "HardwareSerial.h"

#endif // Arduino_h
